#!/bin/bash
total 20
-rwxr--r-- 1 root root 19 Feb  8 10:35 0-current_working_directory
-rwxr--r-- 1 root root 15 Feb  8 11:19 1-listit
-rwxr--r-- 1 root root 17 Feb  8 11:25 2-bring_me_home
-rw-r--r-- 1 root root 12 Feb  8 11:34 3-listfiles
-rw-r--r-- 1 root root 10 Feb  8 10:23 README.md
